graph_variables:
    device: "{{device}}"
query_string: |
        query ($device: [String]) {
            devices(name: $device) {
                name
                device_type {
                slug
                }
                device_role {
                    slug
                }
                platform {
                    name
                    slug
                }
                config_context
                local_asn: cf_device_bgp
                viritual_router_mac: cf_virtual_router_mac
                tags {
                slug
                }
                site {
                    name
                    id
                tenant {
                    slug
                    }
                vlans {
                    name
                    tenant {
                        slug
                    }
                    group {
                        name
                        slug
                    }
                    vid
                    vxlan_rt: cf_vxlan_vlan_rt
                    role {
                    slug
                    }
                }
                }
                interfaces {
                name
                role: cf_role
                virtual_router: cf_virtual_router_ipv4
                vlan_vni: cf_vxlan_vlan_vni
                label
                description
                enabled
                mac_address
                mtu
                mode
                tagged_vlans {
                    name
                    vid
                    group {
                        slug
                        }
                }
                untagged_vlan {
                    name
                    vid
                }
                lag {
                    name
                }
                ip_addresses {
                    address
                    vrf {
                    name
                    rd
                    }
                }
                connected_interface {
                    device {
                    name
                    }
                    name
                    ip_addresses {
                    address
                    }
                }
                }
            }
            }
site_variables:
    site: "{{nb_devices[0]['data']['devices'][0]['site']['name']}}"
site_query_string: |
    query ($site: [String]) {
    sites(name: $site) {
        name
        prefixes {
        prefix
        description
        role {
            name
        }
        }
    }
    }
spine_variables:
    role: "spine"
    dc: "{{nb_devices[0]['data']['devices'][0]['site']['name']}}"
spine_query_string: |
    query ($role: [String], $dc: [String]) {
    devices(role: $role, name__ic: $dc) {
        name
        config_context
        local_asn: cf_device_bgp
        rack {
        name
        }
        platform {
            name
        }
        viritual_router_mac: cf_virtual_router_mac
        tags {
        slug
        }
        site {
            name
        vlans {
            name
            vid
            vxlan_rt: cf_vxlan_vlan_rt
            role {
            slug
            }
        }
        }
        interfaces {
        name
        role: cf_role
        virtual_router: cf_virtual_router_ipv4
        vlan_vni: cf_vxlan_vlan_vni
        label
        description
        mac_address
        enabled
        mode
        lag {
            name
        }
        ip_addresses {
            address
            vrf {
            name
            rd
            }
        }
        connected_interface {
            device {
            name
            }
            name
            ip_addresses {
            address
            }
        }
        }
    }
    }
l3leaf_variables:
    role: "l3leaf"
    dc: "{{nb_devices[0]['data']['devices'][0]['site']['name']}}"
l3leaf_query_string: |
    query ($role: [String], $dc: [String]) {
    devices(role: $role, name__ic: $dc) {
        name
        config_context
        local_asn: cf_device_bgp
        rack {
        name
        }
        device_role {
        name
        }
        platform {
            name
        }
        viritual_router_mac: cf_virtual_router_mac
        tags {
        slug
        }
        site {
            name
        vlans {
            name
            vid
            vxlan_rt: cf_vxlan_vlan_rt
            role {
            slug
            }
        }
        }
        interfaces {
        name
        role: cf_role
        virtual_router: cf_virtual_router_ipv4
        vlan_vni: cf_vxlan_vlan_vni
        label
        description
        mac_address
        enabled
        mode
        lag {
            name
        }
        ip_addresses {
            address
            vrf {
            name
            rd
            }
        }
        connected_interface {
            device {
            name
            }
            name
            ip_addresses {
            address
            }
        }
        }
    }
    }

l2leaf_variables:
    role: "l2leaf"
    dc: "{{nb_devices[0]['data']['devices'][0]['site']['name']}}"
l2leaf_query_string: |
    query ($role: [String], $dc: [String]) {
    devices(role: $role, name__ic: $dc) {
        name
        config_context
        local_asn: cf_device_bgp
        rack {
        name
        }
        device_role {
        name
        }
        platform {
            name
        }
        viritual_router_mac: cf_virtual_router_mac
        tags {
        slug
        }
        site {
            name
        vlans {
            name
            vid
            vxlan_rt: cf_vxlan_vlan_rt
            role {
            slug
            }
        }
        }
        interfaces {
        name
        role: cf_role
        virtual_router: cf_virtual_router_ipv4
        vlan_vni: cf_vxlan_vlan_vni
        label
        description
        mac_address
        enabled
        mode
        lag {
            name
        }
        ip_addresses {
            address
            vrf {
            name
            rd
            }
        }
        connected_interface {
            device {
            name
            }
            name
            ip_addresses {
            address
            }
        }
        }
    }
    }

ip_addresses_query_string: |
    query {
    ip_addresses {
        address
        interface {
        name
        device {
            name
        }
        }
        vrf {
        name
        tenant {
            name
        }
        }
    }
    }

vrf_query_string: |
    query {
    vrfs {
        name
        rd
        tenant {
        name
        }
        vni: cf_vrf_vni
        import_targets {
        name
        }
        export_targets {
        name
        }
    }
    }
