---
#############################################################
# Update Device Layer3 interfaces inherited in Nautobot
#############################################################
- name: Add Layer3 interfaces
  networktocode.nautobot.device_interface:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: no
    device: "{{ item.0.name }}"
    name: "{{ item.1.name }}"
    description: "{{ item.1.description }}"
    type: "{{ item.1.type }}"
    enabled: "{{ item.1.enabled }}"
    mtu: "{{ item.1.mtu }}"
    mgmt_only: "{{ item.1.mgmt_only }}"  
    state: present
  loop: "{{ device_list | subelements('l3_interfaces', 'skip_missing=True') }}"