# ---
# - name: Test cv_configlet_v3
#   hosts: cvp
#   connection: local
#   gather_facts: no
#   collections:
#     - arista.cvp
#   vars:
#     configlet_list:
#       BASE_CONFIG: "templates/configlet_BASE_CONFIG.txt"
#   tasks:
#     - name: "Gather CVP facts {{inventory_hostname}}"
#       arista.cvp.cv_facts:
#         facts:
#           configlets
#       register: CVP_FACTS

#     - name: Create configlets on CVP
#       arista.cvp.cv_configlet_v3:
#         # cvp_facts: "{{ CVP_FACTS.ansible_facts }}"
#         configlets: "{{ configlet_list }}"
#         state: present
#       register: CVP_CONFIGLET_RESULT

#     - debug:
#         msg: "{{ CVP_CONFIGLET_RESULT }}"

---
- name: Test cv_configlet_v3
  hosts: cvp
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  vars:
    configlet_list:
      Test_DYNAMIC_Configlet: "{{lookup('file', 'template/host1-dc1.txt')}}"
  tasks:
    - name: Create configlets on CVP
      cv_configlet_v3:
        configlets: "{{configlet_list}}"
        configlets_notes: "Configlet managed by Ansible"
      register: cvp_configlet