---
all:
  children:
    CVP:
      hosts:
        cvp:
          ansible_httpapi_host: 192.168.130.249
          ansible_host: 192.168.130.249
          ansible_user: arista
          ansible_password: arista123
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: True
          ansible_httpapi_validate_certs: False
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: .venv/bin/python3
        dhcp_server:
          ansible_host: 192.168.130.249
          ansible_user: root
          ansible_password: arista123
          ansible_become_password: arista123
          
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                dc1-spine1:
                  ansible_host: 10.42.0.21
                dc1-spine2:
                  ansible_host: 10.42.0.22
                dc1-spine3:
                  ansible_host: 10.42.0.23
            DC1_L3LEAFS:
              hosts:
                dc1-l3leaf1:
                  ansible_host: 10.42.0.24
                dc1-l3leaf2:
                  ansible_host: 10.42.0.25
                dc1-l3leaf3:
                  ansible_host: 10.42.0.26
                dc1-l3leaf4:
                  ansible_host: 10.42.0.27
                dc1-borderleaf1:
                  ansible_host: 10.42.0.19
                dc1-borderleaf2:
                  ansible_host: 10.42.0.20
            DC1_L2LEAFS:
              hosts:
                dc1-l2leaf1:
                  ansible_host: 10.42.0.28
                dc1-l2leaf2:
                  ansible_host: 10.42.0.29
    DC2:
      children:
        DC2_FABRIC:
          children:
            DC2_SPINES:
              hosts:
                spine1-dc2:
                  ansible_host: 10.42.0.32
                spine2-dc2:
                  ansible_host: 10.42.0.33
                spine3-dc2:
                  ansible_host: 10.42.0.34
            DC2_L3LEAFS:
              hosts:
                borderleaf1-dc2:
                  ansible_host: 10.42.0.30
                borderleaf2-dc2:
                  ansible_host: 10.42.0.31
                leaf1-dc2:
                  ansible_host: 10.42.0.35
                leaf2-dc2:
                  ansible_host: 10.42.0.36
                leaf3-dc2:
                  ansible_host: 10.42.0.37
                leaf4-dc2:
                  ansible_host: 10.42.0.38
            DC2_L2LEAFS:
              hosts:
                host1-dc2:
                  ansible_host: 10.42.0.39
                host2-dc2:
                  ansible_host: 10.42.0.40
    DCI:
      hosts:
        dci:
          ansible_host: 10.42.0.18