---
all:
  children:
    CVP:
      hosts:
        cvp:
          ansible_httpapi_host: 192.168.130.249
          ansible_host: 192.168.130.249
          ansible_user: arista
          ansible_password: arista123
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: True
          ansible_httpapi_validate_certs: False
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: .venv/bin/python3
        dhcp_server:
          ansible_host: 192.168.130.249
          ansible_user: root
          ansible_password: arista123
          ansible_become_password: arista123
          
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                dc1-spine1:
                  ansible_host: 10.42.0.21
                  ansible_network_os: eos
                dc1-spine2:
                  ansible_host: 10.42.0.22
                  ansible_network_os: eos
            DC1_L3LEAFS:
              children:
                DC1_LEAF1:
                  hosts:
                    dc1-leaf1:
                      ansible_host: 10.42.0.24
                      ansible_network_os: eos
                    dc1-leaf2:
                      ansible_host: 10.42.0.25
                      ansible_network_os: eos
            DC1_L2LEAFS:
              hosts:
                dc1-l2leaf1:
                  ansible_host: 10.42.0.28
                  ansible_network_os: eos