---
configuration:
  bgp:
    ibgp:
      l_asn: 65002
      neighbors:
        - 10.2.1.2
        - 10.2.1.3
    ebgp:
      neighbors: 
        24.24.2.1: {r_asn: 400}
    address_family_ipv4:
      agg_network: 155.2.1.0
      agg_mask: 255.255.255.0
      advertised_networks:
        155.2.1.0: {net_mask: 255.255.255.192 }
        155.2.1.64: {net_mask: 255.255.255.192 }
        155.2.1.128: {net_mask: 255.255.255.192 }