---
- name: configuration layer2 trunks {{ inventory_hostname }}
  cisco.ios.ios_config:
    src: add_trunk_interface.j2

- name: Saving the running config on {{ inventory_hostname }}
  ios_config:
    save_when: always

# - name: show interfaces trunk
#   ios_command:
#     commands: 
#       - "show interfaces trunk"
#   register: ios_output

# - name: Print Structured Data
#   debug:
#     msg: "{{ ios_output['stdout'][0] | clay584.genie.parse_genie(command='show interfaces trunk', os='ios')  }}"
#   delegate_to: localhost