---
############################################################
# Pulls down the existing vlan database from a cisco switch
############################################################

- name: Connect to access switches
  hosts: access_switches
  gather_facts: false
  connection: network_cli

  tasks:
  - name: show vlan
    ios_command:
      commands: 
        - "show vlan"
    register: ios_output

  - set_fact:
      vlans : "{{ ios_output['stdout'][0] | clay584.genie.parse_genie(command='show vlan', os='ios') }}"
    
  - name: Vlan validation
    template:
      src: vlan_validation.j2
      dest: print_out.txt

  - debug:
      msg: "print_out.txt"  