router_bgp:
  as: 65002
  router_id: 192.168.0.3
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - maximum-paths 4 ecmp 4
  peer_groups:
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: 65002
      next_hop_self: True
      password: vnEaG8gMeQf3d3cN6PktXQ==
      maximum_routes: 12000
      send_community: all
      route_map_in: RM-MLAG-PEER-IN
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      remote_as: 65001
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: True
      ebgp_multihop: 3
      password: q+VNViP5i4rVjW1cxFv2wA==
      maximum_routes: 0
      send_community: all
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: True
      EVPN-OVERLAY-PEERS:
        activate: False
      MLAG-IPv4-UNDERLAY-PEER:
        activate: True
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  neighbors:
    172.31.0.0:
      peer_group: IPv4-UNDERLAY-PEERS
      description: dc1-spine1_Ethernet2
    172.31.0.4:
      peer_group: IPv4-UNDERLAY-PEERS
      description: dc1-spine2_Ethernet2
    10.255.254.1:
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: dc1-leaf2
    192.168.0.1:
      peer_group: EVPN-OVERLAY-PEERS
      description: dc1-spine1
      remote_as: 65001
    192.168.0.2:
      peer_group: EVPN-OVERLAY-PEERS
      description: dc1-spine2
      remote_as: 65001
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: True
      evpn_hostflap_detection:
        window: 180
        enabled: False
        threshold: 30
  vrfs:
    Tenant_A_WEB_Zone:
      router_id: 192.168.0.3
      rd: 192.168.0.3:12
      route_targets:
        import:
          evpn:
          - 12:12
        export:
          evpn:
          - 12:12
      redistribute_routes:
      - connected
  vlan_aware_bundles:
    rd: 192.168.0.3:12
    route_targets:
      both:
      - 12:12
    redistribute_routes:
    - learned
    vlan: 120
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.42.0.2
service_routing_protocols_model: multi-agent
ip_routing: true
daemon_terminattr:
  ingestgrpcurl:
    ips:
    - 10.42.0.1
  port: 9910
  ingestauth_key: arista123
  ingestvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: False
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 192.168.130.253
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
  - 10.42.0.2
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 4096
  no_spanning_tree_vlan: 4093-4094
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$ZrUR9Ryw6oocY9wD$2V99a9yvz/yK66KpyzQTSOfccNCiJT3cIVSKnXEIr9L1X8CVbSJdpWJ7iLZskV5yamYXs4AypSar1Uvy6tv5P1
  arista:
    privilege: 15
    role: network-admin
    sha512_password: $6$BTve3BGeYZZta.Wh$Q4bKHY3zqRqrU9sIhifHh/TSMIKWfrJjvooKK0B5Jp5HzoJ79AXLJQ9rcH4D6orlmO/r3PFnkH/vxxoINdcmY/
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$Fdyhzjx0eSwH/PuE$R6r30IPAYaTMLW4iJ17I3rIFTU8ah.CS4RRNtKcFAMCM3VaNCoZY.DSxXoYStrr059jc9nLZGBOX2.aoTrXRB0
vrfs:
  MGMT:
    ip_routing: false
  Tenant_A_WEB_Zone:
    ip_routing: true
management_api_http:
  enable_https: True
  enable_vrfs:
    MGMT: {}
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 10.42.0.24/24
    gateway: 10.42.0.2
    type: oob
vlans:
  4093:
    tenant: system
    name: LEAF_PEER_L3_VLAN
    trunk_groups:
    - leaf_peer_l3
  4094:
    tenant: system
    name: MLAG_PEER_VLAN
    trunk_groups:
    - mlag
  120:
    tenant: tenant_a
    name: Tenant_A_WEB_Zone_1
    trunk_groups:
    - tenant_a_web_zone
vxlan_interface:
  Vxlan1:
    description: dc1-leaf1_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
        120:
          vni: 10120
      vrfs:
        Tenant_A_WEB_Zone:
          vni: 12
vlan_interfaces:
  Vlan120:
    description: Tenant_A_WEB_Zone_1
    shutdown: false
    ip_address_virtual: 10.1.20.1/24
    vrf: Tenant_A_WEB_Zone
    mtu: 1500
  Vlan4093:
    description: LEAF_PEER
    shutdown: false
    ip_address_virtual: 
    mtu: 1500
  Vlan4094:
    description: MLAG
    shutdown: false
    ip_address: 10.255.252.0/31
    mtu: 1500
port_channel_interfaces:
  Port-Channel1:
    description: MLAG_PEER_dc1-leaf2_Po1
    type: switched
    mode: trunk
    shutdown: false
    vlans: 4093,4094
    trunk_groups:
    - leaf_peer_l3
    - mlag
  Port-Channel6:
    description: DC1-L2LEAF1_Po6
    type: switched
    mode: trunk
    shutdown: false
    mlag: 6
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.0.3/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.1.1/32
ethernet_interfaces:
  Ethernet1:
    peer: dc1-leaf2
    peer_interface: Ethernet1
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-LEAF2_ETHERNET1
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet2:
    peer: dc1-leaf2
    peer_interface: Ethernet2
    peer_type: mlag_peer
    description: MLAG_PEER_DC1-LEAF2_ETHERNET2
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet3:
    peer: dc1-spine1
    peer_interface: Ethernet2
    peer_type: spine
    description: P2P_LINK_TO_DC1-SPINE1_ETHERNET2
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.0.1/31
  Ethernet4:
    peer: dc1-spine2
    peer_interface: Ethernet2
    peer_type: spine
    description: P2P_LINK_TO_DC1-SPINE2_ETHERNET2
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.31.0.5/31
  Ethernet7:
    peer: dc1-l2leaf1
    peer_interface: Ethernet3
    description: DC1-L2LEAF1_ETHERNET3
    type: switched
    shutdown: false
    channel_group:
      id: 6
      mode: active
mlag_configuration:
  domain_id: DC1_LEAF1
  local_interface: Vlan4094
  peer_address: 10.255.252.1
  peer_link: Port-Channel1
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 192.168.0.0/23 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  RM-MLAG-PEER-IN:
    sequence_numbers:
      10:
        type: permit
        set:
        - origin incomplete
        description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
 