router_bgp:
  as: 65003
  router_id: 192.168.0.6
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: 65003
      next_hop_self: true
      password: vnEaG8gMeQf3d3cN6PktXQ==
      maximum_routes: 12000
      send_community: all
      route_map_in: RM-MLAG-PEER-IN
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      remote_as: 65001
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '3'
      password: q+VNViP5i4rVjW1cxFv2wA==
      send_community: all
      maximum_routes: 0
  address_family_ipv4:
    peer_groups:
      MLAG-IPv4-UNDERLAY-PEER:
        activate: true
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  neighbors:
    10.255.254.5:
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: dc1-leaf4
    192.168.0.1:
      peer_group: EVPN-OVERLAY-PEERS
      description: dc1-spine1
      remote_as: 65001
    192.168.0.2:
      peer_group: EVPN-OVERLAY-PEERS
      description: dc1-spine2
      remote_as: 65001
    192.168.0.3:
      peer_group: EVPN-OVERLAY-PEERS
      description: dc1-spine3
      remote_as: 65001
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.42.0.2
service_routing_protocols_model: multi-agent
ip_routing: true
daemon_terminattr:
  ingestgrpcurl:
    ips:
    - 10.42.0.1
    port: 9910
  ingestauth_key: arista123
  ingestvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 192.168.130.253
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
  - 10.42.0.2
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 4096
  no_spanning_tree_vlan: 4093-4094
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$ZrUR9Ryw6oocY9wD$2V99a9yvz/yK66KpyzQTSOfccNCiJT3cIVSKnXEIr9L1X8CVbSJdpWJ7iLZskV5yamYXs4AypSar1Uvy6tv5P1
  arista:
    privilege: 15
    role: network-admin
    sha512_password: $6$BTve3BGeYZZta.Wh$Q4bKHY3zqRqrU9sIhifHh/TSMIKWfrJjvooKK0B5Jp5HzoJ79AXLJQ9rcH4D6orlmO/r3PFnkH/vxxoINdcmY/
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$Fdyhzjx0eSwH/PuE$R6r30IPAYaTMLW4iJ17I3rIFTU8ah.CS4RRNtKcFAMCM3VaNCoZY.DSxXoYStrr059jc9nLZGBOX2.aoTrXRB0
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 10.42.0.26/24
    gateway: 10.42.0.2
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
vlans:
  4093:
    tenant: system
    name: LEAF_PEER_L3
    trunk_groups:
    - LEAF_PEER_L3
  4094:
    tenant: system
    name: MLAG_PEER
    trunk_groups:
    - MLAG
vlan_interfaces:
  Vlan4093:
    description: MLAG_PEER_L3_PEERING
    shutdown: false
    ip_address: 10.255.254.4/31
    mtu: 9000
  Vlan4094:
    description: MLAG_PEER
    shutdown: false
    ip_address: 10.255.252.4/31
    no_autostate: true
    mtu: 9000
port_channel_interfaces:
  Port-Channel1:
    description: MLAG_PEER_dc1-leaf4_Po1
    type: switched
    shutdown: false
    vlans: 2-4094
    mode: trunk
    trunk_groups:
    - LEAF_PEER_L3
    - MLAG
  Port-Channel6:
    description: DC1-L2LEAF2_Po1
    type: switched
    shutdown: false
    mode: trunk
    mlag: 6
ethernet_interfaces:
  Ethernet1:
    peer: dc1-leaf4
    peer_interface: Ethernet1
    peer_type: mlag_peer
    description: MLAG_PEER_dc1-leaf4_Ethernet1
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet2:
    peer: dc1-leaf4
    peer_interface: Ethernet2
    peer_type: mlag_peer
    description: MLAG_PEER_dc1-leaf4_Ethernet2
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet6:
    peer: dc1-l2leaf2
    peer_interface: Ethernet1
    peer_type: l2leaf
    description: DC1-L2LEAF2_Ethernet1
    type: switched
    shutdown: false
    channel_group:
      id: 6
      mode: active
mlag_configuration:
  domain_id: DC1_LEAF2
  local_interface: Vlan4094
  peer_address: 10.255.252.5
  peer_link: Port-Channel1
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330
route_maps:
  RM-MLAG-PEER-IN:
    sequence_numbers:
      10:
        type: permit
        set:
        - origin incomplete
        description: Make routes learned over MLAG Peer-link less preferred on spines
          to ensure optimal routing
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.0.6/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.1.6/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 192.168.0.0/24 eq 32
      20:
        action: permit 192.168.1.0/24 eq 32
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ip_igmp_snooping:
  globally_enabled: true
vxlan_tunnel_interface:
  Vxlan1:
    description: dc1-leaf3_VTEP
    source_interface: Loopback1
    virtual_router:
      encapsulation_mac_address: mlag-system-id
    vxlan_udp_port: 4789
    vxlan_vni_mappings: {}
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
