static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.42.0.2
service_routing_protocols_model: multi-agent
ip_routing: true
daemon_terminattr:
  ingestgrpcurl:
    ips:
    - 10.42.0.1
    port: 9910
  ingestauth_key: arista123
  ingestvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 192.168.130.253
ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
  - 10.42.0.2
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 16384
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$ZrUR9Ryw6oocY9wD$2V99a9yvz/yK66KpyzQTSOfccNCiJT3cIVSKnXEIr9L1X8CVbSJdpWJ7iLZskV5yamYXs4AypSar1Uvy6tv5P1
  arista:
    privilege: 15
    role: network-admin
    sha512_password: $6$BTve3BGeYZZta.Wh$Q4bKHY3zqRqrU9sIhifHh/TSMIKWfrJjvooKK0B5Jp5HzoJ79AXLJQ9rcH4D6orlmO/r3PFnkH/vxxoINdcmY/
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$Fdyhzjx0eSwH/PuE$R6r30IPAYaTMLW4iJ17I3rIFTU8ah.CS4RRNtKcFAMCM3VaNCoZY.DSxXoYStrr059jc9nLZGBOX2.aoTrXRB0
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 10.42.0.28/24
    gateway: 10.42.0.2
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
ethernet_interfaces:
  Ethernet1:
    peer: dc1-leaf1
    peer_interface: Ethernet6
    peer_type: l3leaf
    description: DC1-LEAF1_Ethernet6
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
  Ethernet2:
    peer: dc1-leaf2
    peer_interface: Ethernet6
    peer_type: l3leaf
    description: DC1-LEAF2_Ethernet6
    type: switched
    shutdown: false
    channel_group:
      id: 1
      mode: active
port_channel_interfaces:
  Port-Channel1:
    description: DC1_LEAF1_Po6
    type: switched
    shutdown: false
    mode: trunk
ip_igmp_snooping:
  globally_enabled: true
