- name: Configuring access switches
  hosts: access_switches
  gather_facts: false
  connection: network_cli
  
  roles:
    - { role: access_switch/add_vlan }
    - { role: access_switch/add_access_interface }
    - { role: access_switch/add_trunk_interface }
    - { role: access_switch/config_validation }