graph_variables:
    device: "{{device}}"
query_string: |
        query ($device: [String]) {
            devices(name: $device) {
                name
                device_type {
                slug
                }
                device_role {
                    slug
                }
                config_context
                local_asn: cf_device_bgp
                viritual_router_mac: cf_virtual_router_mac
                tags {
                slug
                }
                site {
                    id
                tenant {
                    slug
                    }
                vlans {
                    name
                    vid
                    vxlan_rt: cf_vxlan_vlan_rt
                    vlan_vni: cf_vlan_vni
                    role {
                    slug
                    }
                }
                }
                interfaces {
                name
                role: cf_role
                virtual_router: cf_virtual_router_ipv4
                vlan_vni: cf_vxlan_vlan_vni
                int_vrf: cf_int_vrf
                label
                description
                enabled
                mac_address
                mode
                tagged_vlans {
                    name
                    vid
                }
                untagged_vlan {
                    name
                    vid
                }
                lag {
                    name
                }
                ip_addresses {
                    address
                    interface_unit: cf_int_unit
                    vrf {
                    name
                    rd
                    }
                }
                connected_interface {
                    device {
                    name
                    }
                    name
                    ip_addresses {
                    address
                    }
                }
                }
            }
            }
query_vrf: |
        {
        vrfs {
            name
            tenant{
            slug
            }
            rd
            vrf_vni: cf_vrf_vni
            import_targets {
            name
            }
            export_targets {
            name
            }
        }
        }
spine_var: 
    device: "spine"
    site: "{{ nb_devices[0].data.devices[0].site.id }}"

query_spine: |
        query ($device: [String], $site: [String]) {
        devices(name__ic: $device, site_id: $site) {
            name
            config_context
            local_asn: cf_device_bgp
            viritual_router_mac: cf_virtual_router_mac
            tags {
            slug
            }
            interfaces {
            name
            role: cf_role
            virtual_router: cf_virtual_router_ipv4
            vlan_vni: cf_vxlan_vlan_vni
            label
            description
            enabled
            mode
            lag {
                name
            }
            ip_addresses {
                address
                interface_unit: cf_int_unit
                vrf {
                name
                rd
                }
            }
            connected_interface {
                device {
                name
                }
                name
                ip_addresses {
                address
                }
            }
            }
        }
        }
leaf_var: 
    device: "leaf"
    site: "{{ nb_devices[0].data.devices[0].site.id }}"

query_leaf: |
        query ($device: [String], $site: [String]) {
        devices(name__ic: $device, site_id: $site) {
            name
            config_context
            local_asn: cf_device_bgp
            viritual_router_mac: cf_virtual_router_mac
            tags {
            slug
            }
            interfaces {
            name
            role: cf_role
            virtual_router: cf_virtual_router_ipv4
            vlan_vni: cf_vxlan_vlan_vni
            label
            description
            enabled
            mode
            lag {
                name
            }
            ip_addresses {
                address
                interface_unit: cf_int_unit
                vrf {
                name
                rd
                }
            }
            connected_interface {
                device {
                name
                }
                name
                ip_addresses {
                address
                }
            }
            }
        }
        }