- name: Get device data from Nautobot
  set_fact:
    nb_devices: "{{ query('networktocode.nautobot.lookup_graphql', query_string, graph_variables=graph_variables, url=nb_url, token=nb_token) }}"

- name: Get site data from Nautobot
  set_fact:
    nb_sites: "{{ query('networktocode.nautobot.lookup_graphql', site_query_string, graph_variables=site_variables, url=nb_url, token=nb_token) }}"

- name: Get spine devices data from Nautobot
  set_fact:
    nb_spines: "{{ query('networktocode.nautobot.lookup_graphql', spine_query_string, graph_variables=spine_variables, url=nb_url, token=nb_token) }}"

- name: Get l3leaf devices data from Nautobot
  set_fact:
    nb_l3leafs: "{{ query('networktocode.nautobot.lookup_graphql', l3leaf_query_string, graph_variables=l3leaf_variables, url=nb_url, token=nb_token) }}"

- name: Get borderleaf devices data from Nautobot
  set_fact:
    nb_borderleafs: "{{ query('networktocode.nautobot.lookup_graphql', borderleaf_query_string, graph_variables=borderleaf_variables, url=nb_url, token=nb_token) }}"

- name: Get l2leaf devices data from Nautobot
  set_fact:
    nb_l2leafs: "{{ query('networktocode.nautobot.lookup_graphql', l2leaf_query_string, graph_variables=l2leaf_variables, url=nb_url, token=nb_token) }}"

- name: Configuration Assembly
  template:
    src: "dc_fabric_var.j2"
    dest: "inventory/group_vars/{{nb_devices[0]['data']['devices'][0]['site']['name']}}_FABRIC.yaml"