---
#############################################################
# Update Device Disabled interfaces inherited in Nautobot
#############################################################
- name: Add disabled interfaces
  networktocode.nautobot.device_interface:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: no
    data:
      device: "{{ item.0.name }}"
      name: "{{ item.1.name }}"
      type: "{{ item.1.type }}"
      enabled: "{{ item.1.enabled }}" 
    state: present
  loop: "{{ device_list | subelements('disabled_interfaces', 'skip_missing=True') }}"