---
configuration:
  bgp:
    ibgp:
      l_asn: 65002
      neighbors:
        - 10.2.1.1
        - 10.2.1.3
    address_family_ipv4:
      advertised_networks:
        155.2.1.0: {net_mask: 255.255.255.192 }
        155.2.1.64: {net_mask: 255.255.255.192 }
        155.2.1.128: {net_mask: 255.255.255.192 }

