---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: DC1_FABRIC

# Set Maximum spines to allow growth to 8 spines
max_spines: 4

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [spines * total potential leafs * 2]
underlay_p2p_network_summary: 172.31.0.0/24

# IP address range for evpn loopback for all switches in fabric,
# assigned as /32s
# Assign range larger then total spines + total leafs switches
overlay_loopback_network_summary: 192.168.0.0/24

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: 192.168.1.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then
# total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.254.0/27
  mlag_peer: 10.255.252.0/27

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# Disable EVPN host-flap protection
evpn_hostflap_detection:
  enabled: false
  threshold: 30

# Set short_esi prefix to non-default value
evpn_short_esi_prefix: "0000:1234:"

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  platform: vEOS-LAB
  bgp_as: 65001
  # defines the range of acceptable remote ASNs from leaf switches
  leaf_as_range: 65101-65132
  nodes:
    dc1-spine1:
      id: 1
      mgmt_ip: 10.42.0.21/24
      mac_address: 50:00:00:0B:00:00
      
    dc1-spine2:
      id: 2
      mgmt_ip: 10.42.0.22/24
      mac_address: 50:00:00:0C:00:00
      

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    virtual_router_mac_address: 00:dc:00:00:00:0a
    platform: vEOS-LAB
    spines: [dc1-spine1, dc1-spine2]
    uplink_to_spine_interfaces:
      - Ethernet3
      - Ethernet4
    mlag_interfaces:
      - Ethernet1
      - Ethernet2
    mlag_peer_l3_vlan: 4093
    mlag_peer_vlan: 4094
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    DC1_LEAF1:
      platform: vEOS-LAB
      bgp_as: 65002
      nodes:
        dc1-leaf1:
          id: 1
          rack: dc1-leaf-rr-1
          mgmt_ip: 10.42.0.24/24
          mac_address: 50:00:00:0E:00:00
          spine_interfaces:
            - Ethernet2
            - Ethernet2
          uplink_to_spine_interfaces:
            - Ethernet3
            - Ethernet4
        dc1-leaf2:
          id: 2
          rack: dc1-leaf-rr-2
          mgmt_ip: 10.42.0.25/24
          mac_address: 50:00:00:0F:00:00
          spine_interfaces:
            - Ethernet3
            - Ethernet3
          uplink_to_spine_interfaces:
            - Ethernet3
            - Ethernet4
l2leaf:
  defaults:
    platform: vEOS-LAB
    parent_l3leafs: [ dc1-leaf1, dc1-leaf2 ]
    uplink_interfaces:
      - Ethernet3
      - Ethernet4
    mlag_interfaces:
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    DC1_L2LEAF1:
      parent_l3leafs:
        - dc1-leaf1
        - dc1-leaf2
      nodes:
        dc1-l2leaf1:
          id: 1
          mgmt_ip: 10.42.0.28/24
          mac_address: 50:00:00:12:00:00
          l3leaf_interfaces:
            - Ethernet7
            - Ethernet7
#### Override for vEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install, which is not supported in vEOS-LAB.

spine_bgp_defaults:
#  - update wait-for-convergence
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200

leaf_bgp_defaults:
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200

# Upodate p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

custom_structured_configuration_prefix: [ 'my_dci_', 'my_special_dci_', 'override_' ]

# Set Hardware Speed Groups per platform
platform_speed_groups:
  7280R:             # Only setting speed-groups on 7280R platform, so only L3leaf should get this setting.
    25G: [ 3, 2 ]    # Unsorted order, but we should sort output correctly.
    10G: [ 1, 2, 4 ] # Duplicate speed-group 2. Since we sort on key first the result will be 25G for group 2