---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: DC1_FABRIC

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [spines * total potential leafs * 2]
underlay_p2p_network_summary: 172.31.0.0/24

# IP address range for evpn loopback for all switches in fabric,
# assigned as /32s
# Assign range larger then total spines + total leafs switches
overlay_loopback_network_summary: 192.168.0.0/24

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: 192.168.1.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then
# total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.254.0/27
  mlag_peer: 10.255.252.0/27

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  defaults:
    loopback_ipv4_pool: 192.168.0.0/24
    vtep_loopback_ipv4_pool: 192.168.1.0/24
    bgp_as: 65001
  platform: vEOS-LAB
  bgp_as: 65001
  # defines the range of acceptable remote ASNs from leaf switches
  leaf_as_range: 65101-65132
  nodes:
    dc1-spine1:
      id: 1
      mgmt_ip: 10.42.0.21/24
      
    dc1-spine2:
      id: 2
      mgmt_ip: 10.42.0.22/24
      
    dc1-spine3:
      id: 3
      mgmt_ip: 10.42.0.23/24
      

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    spines: [dc1-spine1, dc1-spine2, dc1-spine3]
    uplink_to_spine_interfaces:
      - Ethernet3
      - Ethernet4
      - Ethernet5
    mlag_interfaces:
      - Port-Channel10
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    loopback_ipv4_pool: 192.168.0.0/24
    vtep_loopback_ipv4_pool: 192.168.1.0/24
    mlag_peer_ipv4_pool: 10.255.252.0/27
    mlag_peer_l3_ipv4_pool: 10.255.254.0/27
