---
- name: Create Fabric Group Vars
  hosts: [dc1-spine1, dc1-spine2, dc1-leaf1, dc1-leaf2]
  connection: local
  gather_facts: false

  vars:
    device: "{{inventory_hostname}}"

  roles:
  - { role: dc_group_var_create }
  # - { role: generate_documentation } 