---
configuration:
  bgp:
    ibgp:
      l_asn: 65005
      neighbors:
        - 10.5.1.1
        - 10.5.1.2
    address_family_ipv4:
      advertised_networks:
        155.5.1.0: {net_mask: 255.255.255.192 }
        155.5.1.64: {net_mask: 255.255.255.192 }
        155.5.1.128: {net_mask: 255.255.255.192 }    

