- name: configuring ospf on {{ inventory_hostname }}
  cisco.ios.ios_config:
    src: ospf.j2

- name: Saving the running config on {{ inventory_hostname }}
  ios_config:
    save_when: always

# - name: show ip ospf neighbor
#   ios_command:
#     commands: 
#       - "show ip ospf neighbor"
#   register: ios_output

# - name: Print Structured Data
#   debug:
#     msg: "{{ ios_output['stdout'][0] | clay584.genie.parse_genie(command='show ip ospf neighbor', os='ios')  }}"
#   delegate_to: localhost