---
#############################################################
# Create Site in Nautobot
#############################################################  
- name: Create site with all parameters
  networktocode.nautobot.site:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: no
    data:
      name: "{{ item.name }}"
      status: "{{ item.status }}"
      asn: "{{ item.asn }}"
      time_zone: "{{ item.time_zone }}"
      description: "{{ item.description }}"
      physical_address: "{{ item.physical_address }}"
      shipping_address: "{{ item.shipping_address }}"
      latitude: "{{ item.latitude }}"
      longitude: "{{ item.longitude }}"
      contact_name: "{{ item.contact_name }}"
      contact_phone: "{{ item.contact_phone }}"
      contact_email: "{{ item.contact_email }}"
      slug: "{{ item.slug }}"
      comments: "{{ item.comments }}"
    state: present
  loop: "{{ sites }}"