---
configuration:
  bgp:
    ibgp:
      l_asn: 65004
      neighbors:
        - 10.4.1.2
        - 10.4.1.3
    ebgp:
      neighbors: 
        24.24.4.1: {r_asn: 400}
    address_family_ipv4:
      agg_network: 155.4.1.0
      agg_mask: 255.255.255.0
      advertised_networks:
        155.4.1.0: {net_mask: 255.255.255.192 }
        155.4.1.64: {net_mask: 255.255.255.192 }
        155.4.1.128: {net_mask: 255.255.255.192 }