---
- name: Add new vlan to vlan database on {{ inventory_hostname }}
  cisco.ios.ios_config:
    src: add_vlan.j2

- name: Making SW1 spanning tree root bridge for added vlans
  cisco.ios.ios_config:
    src: spanning_root_bridge.j2

- name: Saving the running config on {{ inventory_hostname }}
  ios_config:
    save_when: always    

# - name: show vlan
#   ios_command:
#     commands: 
#       - "show vlan"
#   register: ios_output

# - name: Print Structured Data
#   debug:
#     msg: "{{ ios_output['stdout'][0] | clay584.genie.parse_genie(command='show vlan', os='ios')  }}"
#   delegate_to: localhost