---
- name: configuring layer2 access interfaces on {{ inventory_hostname }}
  cisco.ios.ios_config:
    src: add_access_interface.j2

- name: Saving the running config on {{ inventory_hostname }}
  ios_config:
    save_when: always    

# - name: show interfaces switchport
#   ios_command:
#     commands: 
#       - "show interfaces switchport"
#   register: ios_output

# - name: Print Structured Data
#   debug:
#     msg: "{{ ios_output['stdout'][0] | clay584.genie.parse_genie(command='show interfaces switchport', os='ios')  }}"
#   delegate_to: localhost