---
configuration:
  bgp:
    ibgp:
      l_asn: 65003
      neighbors:
        - 10.3.1.1
        - 10.3.1.2
    address_family_ipv4:
      advertised_networks:
        155.3.1.0: {net_mask: 255.255.255.192 }
        155.3.1.64: {net_mask: 255.255.255.192 }
        155.3.1.128: {net_mask: 255.255.255.192 }    

