- name: Configuring core switches
  hosts: core_switches
  gather_facts: false
  connection: network_cli
  
  roles:
    - { role: core_switch/add_vlan }
    - { role: core_switch/add_trunk_interface }
    - { role: core_switch/add_l3_interface }
    - { role: core_switch/add_ospf }
    - { role: core_switch/add_bgp }