---
- name: update interface description and admin status
  cisco.ios.ios_interfaces:
    config:
    - name: "{{ interface_id }}"
      description: "{{ description }}"
      enabled: "{{ enabled }}"   
    state: replaced

- name: update interface mtu
  cisco.ios.ios_interfaces:
    config:
    - name: "{{ interface_id }}"
      mtu: "{{ mtu }}"      
    state: replaced
  when: mtu != "None"

- name: update access vlan
  cisco.ios.ios_l2_interfaces:
    config:
    - name: "{{ interface_id }}"
      mode: "{{ mode }}"
      access:
        vlan: "{{ untagged_vlan }}"
    state: replaced  
  when: mode == "access"

- name: udpate trunk vlans
  cisco.ios.ios_l2_interfaces:
    config:
    - name: "{{ interface_id }}"
      mode: "{{ mode | replace('tagged', 'trunk') }}"
      trunk:
        allowed_vlans: "{{ tagged_vlans }}"
        native_vlan: "{{ untagged_vlan }}"
    state: replaced
  when: mode == "tagged"

- name: updating L3 configuration
  cisco.ios.ios_config:
    src: l3_interface.j2
    save_when: always
  when: label == "layer3"