# - name: configuring dhcp server on {{ inventory_hostname }}
#   cisco.ios.ios_config:
#     src: dhcp_pool.j2

# - name: Saving the running config on {{ inventory_hostname }}
#   ios_config:
#     save_when: always

# - name: Get Data From Device
#   ios_command:
#     commands: 
#       - "show bgp summary"
#   register: ios_output

# - name: Print Structured Data
#   debug:
#     msg: "{{ ios_output['stdout'][0] | clay584.genie.parse_genie(command='show bgp summary', os='ios')  }}"
#   delegate_to: localhost

- name: building vlans configuration
  template:
    src: "dhcp_pool.j2"
    dest: "{{ inventory_hostname }}_dhcp_pool_test.txt"